name: 'Great-Expectations-Data'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  uses: great-expectations/great_expectations_action@v0.2
  
  with:
    CHECKPOINTS: "my_checkpoint"
    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    GE_HOME: 'great_expectations'
    DEBUG: true
    ACTION_DOCS_LOCATION:
    FAILING_CHECKPOINTS:
    PASSING_CHECKPOINTS:
    NETLIFY_DOCS_URL:
    CHECKPOINT_FAILURE_FLAG:
